name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish to Eldonexus
    runs-on: ubuntu-latest
    environment: publish

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: oracle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Apply API patches
        run: |
          git config --global user.email "tabletop.paper@workflow.github.com"
          git config --global user.name "TabletopPaper"
          ./gradlew :applyPaperSingleFilePatches
          ./gradlew :applyAllPatches

      - name: Publish
        run: ./gradlew publish -PpublishDevBundle
        env:
          NEXUS_USERNAME: "${{ secrets.NEXUS_USERNAME }}"
          NEXUS_PASSWORD: "${{ secrets.NEXUS_PASSWORD }}"
